syntax = "proto3";

package rawstproto;

message Chunk {
    uint64 x_offset = 1;
    uint64 y_offset = 2;
    uint64 downloaded = 3;

}

message VecOfChunks {
    repeated Chunk multiple_chunks = 1;

}

message HttpTask {

    string iri = 1;
    string file_name = 2;
    uint64 total_downloaded = 3;
    oneof ChunkType {
        Chunk chunk = 4;
        VecOfChunks multiple_chunks = 5;

    };
    map<string, string> additional_headers = 6;
    string timestamp = 7;
    map<string, string> headers = 8;

}

message ProgressData {
    uint64 chunk_size = 1;

}

service RawstDownload {
    rpc Download(HttpTask) returns (stream ProgressData) {}
}