syntax = "proto3";

package rawstproto;

message DownloadArgs {
    optional uint32 threads = 1;
    optional string input = 2;
    repeated string output_file_path = 3;
    optional string headers_file_path = 4;
}

message ResumeArgs {
    repeated string download_ids = 1;
}

message HistoryArgs {
    bool show = 1;
    bool clear = 2;
}

message Config {
}

message Request {
    string argument_type = 1;

    oneof command_args {
        DownloadArgs download_args = 2;
        ResumeArgs resume_args = 3;
        HistoryArgs history_args = 4;
        Config config_args = 5;
    };

    string color = 6;
    optional string log_verbosity = 7;
    optional string verbosity = 8;
}

message Response {
    string output = 1;
}

service RawstDownload {
    rpc Send(Request) returns (Response);
}